[package]
name = "day-6"
version = "0.1.0"
authors = ["Andrew Gaspar <andrew.gaspar@outlook.com>"]
edition = "2018"

[dependencies]
clap = "2.32"
rayon = "1.0"
ndarray = "0.12.1"
ndarray-parallel = "0.9.0"